# Generated by Django 2.2.27 on 2022-03-19 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220318_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 19, 10, 6, 48, 102660), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 3, 19, 10, 6, 48, 102660), verbose_name='Дата'),
        ),
    ]
